account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import show_dashboard, registration, edit_profile, user_list, user_detail, user_follow

app_name = "account"

urlpatterns = [
    path("", show_dashboard, name="dashboard"),

    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    path("password_change/", auth_views.PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/", auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path("password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path("registration/", registration, name="registration"),

    path("edit_profile/", edit_profile, name="edit_profile"),

    path("user/", user_list, name="user_list"),
    path("user/follow/", user_follow, name="user_follow"),
    path("user/<username>/", user_detail, name="user_detail"),
]

images/urls.py
from django.urls import path

from .views import image_download, image_detail, image_like, image_list

app_name = "images"

urlpatterns = [
    path("", image_list, name="list"),
    path("download/", image_download, name="download"),
    path("detail/<int:id>/<slug:slug>/", image_detail, name="detail"),
    path("like/", image_like, name="like"),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace="account")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace="images")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class Profile(models.Model):
    """Расширение стандартной модели пользователя"""
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    birth_date = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True)

    def __str__(self):
        return f"User's profile {self.user.username}"


class Contact(models.Model):
    """Связующая таблица для подписки пользователей друг на друга"""
    subscribed_from_user = models.ForeignKey(
        "auth.User",
        related_name="rel_from_set",
        on_delete=models.CASCADE,
    )
    subscribed_to_user = models.ForeignKey(
        "auth.User",
        related_name="rel_to_set",
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    def __str__(self):
        return f"{self.subscribed_from_user} follows {self.subscribed_to_user}"

    class Meta:
        ordering = ("-created",)


User.add_to_class('following',
                  models.ManyToManyField(
                      'self',
                      through=Contact,
                      related_name='followers',
                      symmetrical=False
                  )
                )

account/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class LoginForm(forms.Form):
    """Форма логирования"""
    username = forms.CharField(label="Имя пользователя или email", max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    """Форма регистрации"""
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat your password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "first_name", "email")

    def clean_password2(self):
        data = self.cleaned_data
        if data["password1"] != data["password2"]:
            raise forms.ValidationError("Password1 and password2 don't match!")
        return data["password2"]


class BaseUserEditForm(forms.ModelForm):
    """Форма редактирования стандартных данных пользователя"""

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")


class AddUserEditForm(forms.ModelForm):
    """Форма редактирования расширенных полей стандартной модели пользователя"""

    class Meta:
        model = Profile
        fields = ("birth_date", "photo")

account/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.views.decorators.http import require_POST

from .forms import LoginForm, RegistrationForm, BaseUserEditForm, AddUserEditForm
from .models import Profile, Contact
from actions.urils import create_action
from actions.models import Action


@login_required
def show_dashboard(request):
    """Отображает рабочий стол аккаунта"""
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list("id", flat=True)
    if following_ids:
        actions = actions.filter(user_id__in=following_ids)
    actions = actions.select_related("user", "user__profile").prefetch_related("target")[:10]
    context = {
        "section": "dashboard",
        "actions": actions,
    }
    return render(request, "account/dashboard.html", context)


def registration(request):
    """Обработчик регистрации пользователя"""
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data["password1"])
            Profile.objects.create(user=new_user)
            new_user.save()
            create_action(request.user, "craeted an account")

            context = {
                "new_user": new_user,
            }

            return render(request, "account/registration_done.html", context)

    else:
        form = RegistrationForm()
        context = {
            "form": form,
        }
        return render(request, "account/registration.html", context)


@login_required
def edit_profile(request):
    """Обработчик редактирования профиля пользователя"""
    if request.method == "POST":
        base_form = BaseUserEditForm(
            instance=request.user,
            data=request.POST,
        )
        add_form = AddUserEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES,
        )

        if base_form.is_valid() and add_form.is_valid():
            base_form.save()
            add_form.save()
            messages.success(request, "Profile was changed successfully!")
        else:
            messages.error(request, "There was something wrong! Try again.")

    else:
        base_form = BaseUserEditForm(instance=request.user)
        add_form = AddUserEditForm(instance=request.user.profile)

    context = {
        "base_form": base_form,
        "add_form": add_form,
    }

    return render(request, "account/edit_profile.html", context)


def user_list(request):
    """Отображение списка всех пользователей"""
    users = User.objects.filter(is_active=True)
    context = {
        "section": "people",
        "users": users,
    }
    return render(request, "account/user/list.html", context)


def user_detail(request, username):
    """Отображение конкретного пользователя"""
    user = get_object_or_404(User, username=username, is_active=True)
    context = {
        "section": "people",
        "user": user,
    }
    return render(request, "account/user/detail.html", context)


@require_POST
@login_required
def user_follow(request):
    """Обработчик подписки на других пользователей"""
    user_id = request.POST.get("id")
    action = request.POST.get("action")
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == "follow":
                Contact.objects.get_or_create(subscribed_from_user=request.user, subscribed_to_user=user)
                create_action(request.user, "following", user)
            else:
                Contact.objects.filter(subscribed_from_user=request.user, subscribed_to_user=user).delete()
            return JsonResponse({"status": "ok"})
        except User.DoesNotExist:
            return JsonResponse({"status": "ok"})
    return JsonResponse({"status": "ok"})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} {% endblock title %}</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div id="header">
            <span class="logo">Bookmarks</span>
            {% if request.user.is_authenticated %}
                <ul class="menu">
                    <li {% if section == "dashboard" %}
                            class="selected"
                        {% endif %}>
                        <a href="{% url 'account:dashboard' %}">My dashboard</a>
                    </li>
                    <li {% if section == "images" %}class="selected"{% endif %}>
                        <a href="{% url 'images:list' %}">Images</a>
                    </li>
                    <li {% if section == "people" %}
                            class="selected"
                        {% endif %}>
                        <a href="{% url 'account:user_list' %}">People</a>
                    </li>
                </ul>
            {% endif %}

            <span class="user">
              {% if request.user.is_authenticated %}
                Hello, {{ request.user.first_name }}!
                <a href="{% url 'account:logout' %}">Logout</a>
              {% else %}
                <a href="{% url 'account:login' %}">Login</a>
              {% endif %}
            </span>
        </div>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }}
                        <a href="#" class="close">x</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

        <div id="content">
            {% block content %} {% endblock content %}
        </div>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
      <script>
        var csrftoken = Cookies.get('csrftoken');
        function csrfSafeMethod(method) {
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
          beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
          }
        });
        $(document).ready(function(){
          {% block domready %}
          {% endblock %}
           });
      </script>
    </body>
</html>