images/urls.py
from django.urls import path

from .views import image_download, image_detail, image_like, image_list

app_name = "images"

urlpatterns = [
    path("", image_list, name="list"),
    path("download/", image_download, name="download"),
    path("detail/<int:id>/<slug:slug>/", image_detail, name="detail"),
    path("like/", image_like, name="like"),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace="account")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace="images")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify


class Image(models.Model):
    """Модель отображения картинки"""
    title = models.CharField("Название", max_length=200)
    image = models.ImageField("Картинка", upload_to="images/%Y/%m/%d")
    description = models.TextField("Описание", blank=True)
    slug = models.SlugField("Слаг", max_length=200, blank=True)
    url = models.URLField("URL")
    created = models.DateTimeField("Дата создания", auto_now_add=True, db_index=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="images_created",
        verbose_name="пользователь, добавивший картинку",
    )
    like = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="liked_images",
        verbose_name="лайк",
    )
    count_likes = models.PositiveIntegerField(default=0, db_index=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('images:detail', kwargs={"id": self.id, "slug": self.slug})

    def save(self, *args, **kwargs):
        """Добавление слага по заголовку"""
        if not self.slug:
            self.slug = slugify(self.title)
        super(Image, self).save(*args, **kwargs)

images/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile
from django.utils.text import slugify

from urllib import request

from .models import Image


class ImageDownloadForm(forms.ModelForm):
    """Форма загрузки картинки"""

    class Meta:
        model = Image
        fields = ("url", "title", "description")
        widgets = {"url": forms.HiddenInput}

    def clean_url(self):
        url: str = self.cleaned_data["url"]
        extension = url.rsplit(".", 1)[1].lower()
        if extension not in ("jpg", "jpeg", "png"):
            raise ValidationError("This url contained not allowed extension format of the picture")
        return url

    def save(self, commit=True):
        image = super(ImageDownloadForm, self).save(commit=False)
        image_url: str = self.cleaned_data["url"]
        image_name = f"{slugify(image.title)}.{image_url.rsplit('.', 1)[1].lower()}"

        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)

        if commit:
            image.save()
        return image

images/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.http import require_POST

from .forms import ImageDownloadForm
from .models import Image
from actions.urils import create_action


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


@login_required
def image_download(request):
    """Отображает форму добавления картинки.
    Загружает картинку и привязывает её к пользователю"""
    if request.method == "POST":
        form = ImageDownloadForm(request.POST)
        if form.is_valid():
            new_picture = form.save(commit=False)
            new_picture.user = request.user
            new_picture.save()
            create_action(request.user, "bookmarked image", new_item)
            messages.success(request, "Image download successfully!")
            return redirect(new_picture.get_absolute_url())

    else:
        form = ImageDownloadForm(request.GET)

    context = {
        "form": form,
        "section": "images",
    }
    return render(request, "images/image/download.html", context)


def image_detail(request, id, slug):
    """Обработчик для редактирования сведений об изображении"""
    image = get_object_or_404(Image, id=id, slug=slug)
    context = {
        "image": image,
        "section": "images",
    }
    return render(request, "images/image/detail.html", context)


def image_list(request):
    """Обработчик постраничного отображения картинок
    через стандартный запрос и через ajax-запрос"""
    images = Image.objects.all()
    paginator = Paginator(images, 5)
    page = request.GET.get("page")
    try:
        images = paginator.page("page")
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if is_ajax(request=request):
            return HttpResponse("")
        images = paginator.page(paginator.num_pages)

    context = {
        "images": images,
        "section": "images",
    }
    if is_ajax(request=request):
        return render(request, "images/image/list_ajax.html", context)
    return render(request, "images/image/list.html", context)


@login_required
@require_POST
def image_like(request):
    """Обработчик лайков на картинке"""
    image_id = request.POST.get("id")
    action = request.POST.get("action")

    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == "like":
                image.like.add(request.user)
                create_action(request.user, "likes", image)
            else:
                image.like.remove(request.user)
            return JsonResponse({"status": "ok"})
        except Exception:
            pass

    return JsonResponse({"status": "ok"})

images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
  <h1>{{ image.title }}</h1>
  {% load thumbnail %}

  {% thumbnail image.image "300" as im %}
    <a href="{{ image.image.url }}">
      <img src="{{ im.url }}" class="image-detail">
    </a>
  {% endthumbnail %}

  {% with total_likes=image.like.count users_like=image.like.all %}
    <div class="image-info">
      <div>
        <span class="count">
         <span class="total">{{ total_likes }}</span>
         like{{total_likes|pluralize}}
        </span>
        <span class="count">
          {{ total_views }} view{{ total_views|pluralize }}
        </span>
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>
      </div>
      {{ image.description|linebreaks }}
    </div>
    <div class="image-likes">
      {% for user in image.like.all %}
        <div>
          <img src="{{ user.profile.photo.url }}">
          <p>{{ user.first_name }}</p>
        </div>
      {% empty %}
        Nobody likes this image yet.
      {% endfor %}
    </div>
  {% endwith %}
{% endblock %}

{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "images:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');

          // toggle data-action
          $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
          // toggle link text
          $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

          // update total likes
          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
        }
      }
    );
  });
{% endblock domready %}

images/templates/images/image/download.html
{% extends "base.html" %}

{% block title %}Download an image{% endblock title %}

{% block content %}

<h1>Download an image</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Download">
</form>

{% endblock content %}

images/templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock title %}

{% block content %}
    <h1>Images bookmarked</h1>
    <div id="images-list">
        {% include "images/image/list_ajax.html" %}
    </div>
{% endblock content %}

{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
     block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
       if(data == '') {
          empty_page = true;
        }
        else {
          block_request = false;
          $('#image-list').append(data);
        }
      });
    }
  });
{% endblock %}

images/templates/images/image/list_ajax.html
{{% load thumbnail %}

{% for image in images %}
  <div class="image">
    <a href="{{ image.get_absolute_url }}">
      {% thumbnail image.image "300x300" crop="100%" as im %}
        <a href="{{ image.get_absolute_url }}">
          <img src="{{ im.url }}">
        </a>
      {% endthumbnail %}
    </a>
    <div class="info">
      <a href="{{ image.get_absolute_url }}" class="title">
        {{ image.title }}
      </a>
    </div>
  </div>
{% endfor %}